replicaCount: 2

image:
  repository: jonghyunjoo1235/apigateway-service
  pullPolicy: IfNotPresent
  tag: 1.0.0

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: 34.84.244.202
      paths:
        - /
