apiVersion: v1
kind: Namespace
metadata:
  name: mysql-concert-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-payment-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-user-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-seat-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-reservation-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-wallet-ns
