apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
  namespace: kafka
spec:
  kafka:
    replicas: 3
    image: quay.io/strimzi/kafka:latest-kraft
    config:
      process.roles: "broker,controller"
      node.id: 1
      controller.quorum.voters: "1@my-kafka-0:9093,2@my-kafka-1:9093,3@my-kafka-2:9093"
      listeners: |
        EXTERNAL://:9094
        INTERNAL://:9092
        CONTROLLER://:9093
      advertised.listeners: |
        EXTERNAL://my-kafka-0.kafka.svc.cluster.local:9094
        INTERNAL://my-kafka-0.kafka.svc.cluster.local:9092
      listener.security.protocol.map: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      inter.broker.listener.name: "INTERNAL"
      controller.listener.names: "CONTROLLER"
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 5Gi
  entityOperator: {}  # 사용하지 않으면 생략 가능
